### ISSUE TITLE
Molecule Polarity master checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#53]
## Design
- [x] **Sim folder and design doc created** (Date: 2013?) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- `N/A` **Sim suggestions doc reviewed**
- `N/A` **Learning goals and standards identified** (Date: //)
- `N/A` **Design concept complete**  (Date: //)
- `N/A` **Wireframes complete** (Date: //) 
- `N/A` **Mockups complete** (Date: //) 
  - `N/A`Mockups checked for colorblind and greyscale
-`N/A` **Features for PhET-iO discussion** 
-`N/A` **Interviews complete** (Date: //) 
  - `N/A` Results reported to team
  - `N/A` Notes pasted into design doc
  - `N/A` Back-up of interviews
- `N/A` **Lead designer "sign off"** (Date: //) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped), see #54
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [ ] Sim primer draft
  - [x] Verify credits, see #28
- [ ] **Post-publication items** 
  - [x] Add the simulation to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - `N/A` Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 2/3/14)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ files
- [x] **Development started** (Date: 2/3/14)
- [x] **Sim is "feature complete"** (Date: 3/10/14)
- [x] **Code review completed** (Date: 7/20/17) 
- [x] **Published** (Date: 7/26/17) 
  - [x] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [x] **Dev testing started** (Date: 7/17/17) 
- [x] **Dev testing completed** (Date: 7/20/17) 
- [x] **First RC published** (Date: 7/21/2017)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 7/25/17)

**Comment by pixelzoom** [comment]
@emily-phet I realize that the HTML5 version of this sim started in 2014 (or possibly late 2013), and that you were assigned as design lead late in the process. But where possible, please complete the Design portion of this check list.

**Comment by emily-phet** [comment]
@pixelzoom That will not be possible in a reasonable time frame. I'm in the midst of three consecutive weeks of data collection in Georgia, two grant proposals, two grant reports, and assorted other things. 
@ariel-phet Please assign this to someone else.

**Comment by pixelzoom** [comment]
Searching the "PhET File" folder on Google docs, I don't see an design doc for the HTML5 version. Perhaps one doesn't exist.  I do see "Molecule Polarity HTML5.ai", but it doesn't look useful, should probably be deleted.

**Comment by pixelzoom** [comment]
@ariel-phet Perhaps we can skip many of the Design items? I've replaced check boxes with `N/A` for items that I don't think we can (or should) complete.  If you disagree with any of these `N/A` choices, feel free to convert them back to check boxes.

**Comment by pixelzoom** [comment]
Sim is published, all development-related tasks are completed.

**Comment by ariel-phet** [comment]
Closing
